ktor:
    application:
        modules:
            - com.example.ApplicationKt.module
    deployment:
        port: ${PORT:9090}
        host: ${HOST:0.0.0.0}

database:
    url: ${DB_URL:jdbc:mysql://localhost:3306/barber_shop}
    driver: com.mysql.cj.jdbc.Driver
    user: ${DB_USER:BS}
    password: ${DB_PASSWORD:barbershop}

server:
    environment: ${ENVIRONMENT:production}
